services:
  catalogdb:
    image: postgres:15-alpine
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
   
  basketdb:
    image: postgres:15-alpine

  distributedcache:
    image: "redis"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
        context: .
        dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
        context: .
        dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:  
