services:
  catalogdb:
    image: postgres:15-alpine
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
        context: .
        dockerfile: Services/Catalog/Catalog.Api/Dockerfile

volumes:
  postgres_catalog:
